# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('fees', models.IntegerField(default=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('adult', models.IntegerField(default=1)),
                ('child', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('mobile', models.BigIntegerField(null=True)),
            ],
        ),
    ]
